from __future__ import annotations

from typing import Any


CONTRACT_CLAUSE_CATALOG: list[dict[str, str]] = [
    {
        "clause_id": "CLS-001",
        "category": "Contract Term",
        "clause_title": "Effective Date",
        "summary_citation": "Agreement effective from 01-Jan-2025 with 20-year term ending 31-Dec-2044.",
        "applies_to_transactions": "All Transactions",
    },
    {
        "clause_id": "CLS-002",
        "category": "Contract Term",
        "clause_title": "Settlement Frequency",
        "summary_citation": "Settlements must occur on a quarterly basis.",
        "applies_to_transactions": "Settlement, Reconciliation",
    },
    {
        "clause_id": "CLS-003",
        "category": "Contract Term",
        "clause_title": "Valuation Frequency",
        "summary_citation": "Valuation and actuarial calculations performed monthly.",
        "applies_to_transactions": "Valuation, Rollforward, Cashflow Projection",
    },
    {
        "clause_id": "CLS-004",
        "category": "Population Coverage",
        "clause_title": "Covered Population Definition",
        "summary_citation": "Covered population includes active pensioners, deferred members, and eligible surviving spouses from approved population files.",
        "applies_to_transactions": "Population Processing, Floating Leg",
    },
    {
        "clause_id": "CLS-005",
        "category": "Population Coverage",
        "clause_title": "Included Benefits",
        "summary_citation": "Covered benefits include pension payments, spouse continuation, GMP obligations, inflation-linked increases.",
        "applies_to_transactions": "Floating Leg, Liability Valuation",
    },
    {
        "clause_id": "CLS-006",
        "category": "Population Coverage",
        "clause_title": "Excluded Benefits",
        "summary_citation": "Lump sum death benefits, admin expenses, healthcare benefits excluded from coverage.",
        "applies_to_transactions": "Settlement, Liability Calculation",
    },
    {
        "clause_id": "CLS-007",
        "category": "Data Processing",
        "clause_title": "File Submission Frequency",
        "summary_citation": "Cedant must provide operational files at agreed frequencies depending on file type.",
        "applies_to_transactions": "File Ingestion, Processing",
    },
    {
        "clause_id": "CLS-008",
        "category": "Data Processing",
        "clause_title": "Mortality File Frequency",
        "summary_citation": "Mortality/death files must be submitted weekly.",
        "applies_to_transactions": "Mortality Processing, Floating Leg",
    },
    {
        "clause_id": "CLS-009",
        "category": "Data Processing",
        "clause_title": "Pension Status Update Frequency",
        "summary_citation": "Pension status updates must be submitted monthly.",
        "applies_to_transactions": "Population Management",
    },
    {
        "clause_id": "CLS-010",
        "category": "Data Processing",
        "clause_title": "Settlement Activity Report Frequency",
        "summary_citation": "Settlement activity reports must be delivered quarterly.",
        "applies_to_transactions": "Settlement, Reconciliation",
    },
    {
        "clause_id": "CLS-011",
        "category": "Data Processing",
        "clause_title": "Discount Curve Frequency",
        "summary_citation": "Future discount factor files must be submitted quarterly.",
        "applies_to_transactions": "Valuation, Discounting",
    },
    {
        "clause_id": "CLS-012",
        "category": "Data Processing",
        "clause_title": "Inflation Assumption Frequency",
        "summary_citation": "Inflation assumption files submitted quarterly.",
        "applies_to_transactions": "Cashflow Projection, Valuation",
    },
    {
        "clause_id": "CLS-013",
        "category": "Data Security",
        "clause_title": "SFTP Transfer Requirement",
        "summary_citation": "All files transmitted via encrypted SFTP.",
        "applies_to_transactions": "File Processing",
    },
    {
        "clause_id": "CLS-014",
        "category": "Data Security",
        "clause_title": "Encryption Standard",
        "summary_citation": "Files must use PGP encryption and SHA-256 checksum validation.",
        "applies_to_transactions": "Compliance, Operational Controls",
    },
    {
        "clause_id": "CLS-015",
        "category": "Data Processing",
        "clause_title": "File Validation Rules",
        "summary_citation": "Files validated for duplicates, invalid identifiers, missing mortality status, inconsistent spouse linkage.",
        "applies_to_transactions": "Validation, Exception Handling",
    },
    {
        "clause_id": "CLS-016",
        "category": "Operational SLA",
        "clause_title": "File Ingestion SLA",
        "summary_citation": "File ingestion must complete within 2 hours.",
        "applies_to_transactions": "Operations",
    },
    {
        "clause_id": "CLS-017",
        "category": "Operational SLA",
        "clause_title": "Validation SLA",
        "summary_citation": "Validation must complete within 4 hours.",
        "applies_to_transactions": "Operations",
    },
    {
        "clause_id": "CLS-018",
        "category": "Operational SLA",
        "clause_title": "Exception Identification SLA",
        "summary_citation": "Exceptions identified same business day.",
        "applies_to_transactions": "Operations, Worklist",
    },
    {
        "clause_id": "CLS-019",
        "category": "Operational SLA",
        "clause_title": "Reprocessing SLA",
        "summary_citation": "Reprocessing to complete within 1 business day.",
        "applies_to_transactions": "File Reprocessing",
    },
    {
        "clause_id": "CLS-020",
        "category": "Population Processing",
        "clause_title": "Liability Recalculation Trigger",
        "summary_citation": "Liability recalculation triggered by death notifications, spouse additions, pension amount changes, deferred-active transitions.",
        "applies_to_transactions": "Floating Leg, Settlement",
    },
    {
        "clause_id": "CLS-021",
        "category": "Fixed Leg",
        "clause_title": "Fixed Leg Definition",
        "summary_citation": "Fixed leg represents projected liability cashflows using actuarial assumptions.",
        "applies_to_transactions": "Fixed Leg Calculation",
    },
    {
        "clause_id": "CLS-022",
        "category": "Fixed Leg",
        "clause_title": "Mortality Table Basis",
        "summary_citation": "CPM2014 Public Sector mortality table to be used.",
        "applies_to_transactions": "Actuarial Calculation",
    },
    {
        "clause_id": "CLS-023",
        "category": "Fixed Leg",
        "clause_title": "Longevity Improvement Assumption",
        "summary_citation": "Longevity improvement assumption fixed at 1.5% annually.",
        "applies_to_transactions": "Pricing, Valuation",
    },
    {
        "clause_id": "CLS-024",
        "category": "Fixed Leg",
        "clause_title": "Inflation Assumption",
        "summary_citation": "Long-term inflation assumption fixed at 2.25%.",
        "applies_to_transactions": "Cashflow Projection",
    },
    {
        "clause_id": "CLS-025",
        "category": "Fixed Leg",
        "clause_title": "Discount Curve Source",
        "summary_citation": "Discount curve derived from Government of Canada bond yields.",
        "applies_to_transactions": "Discounting, PV Calculations",
    },
    {
        "clause_id": "CLS-026",
        "category": "Fixed Leg",
        "clause_title": "Fixed Leg Formula",
        "summary_citation": "Fixed Leg = Present Value(Expected Pension Payments).",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-027",
        "category": "Floating Leg",
        "clause_title": "Floating Leg Definition",
        "summary_citation": "Floating leg equals actual pension benefit cashflows paid to surviving members.",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-028",
        "category": "Floating Leg",
        "clause_title": "Included Floating Leg Components",
        "summary_citation": "Includes pension payments, spouse benefits, inflation increases, guaranteed payments.",
        "applies_to_transactions": "Floating Leg",
    },
    {
        "clause_id": "CLS-029",
        "category": "Floating Leg",
        "clause_title": "Floating Leg Formula",
        "summary_citation": "Floating Leg = Sum(Actual Eligible Pension Payments).",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-030",
        "category": "Floating Leg",
        "clause_title": "Mortality Impact Rule",
        "summary_citation": "Mortality events reduce future floating leg obligations effective from date of death.",
        "applies_to_transactions": "Mortality Processing",
    },
    {
        "clause_id": "CLS-031",
        "category": "Settlement",
        "clause_title": "Settlement Currency",
        "summary_citation": "All settlements denominated in CAD.",
        "applies_to_transactions": "Payments",
    },
    {
        "clause_id": "CLS-032",
        "category": "Settlement",
        "clause_title": "Settlement Lag",
        "summary_citation": "Settlement payments due T+10 business days after quarter end.",
        "applies_to_transactions": "Payments",
    },
    {
        "clause_id": "CLS-033",
        "category": "Settlement",
        "clause_title": "Net Settlement Formula",
        "summary_citation": "Net settlement = Floating Leg - Fixed Leg +/- Adjustments.",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-034",
        "category": "Reconciliation",
        "clause_title": "Settlement Reconciliation Requirement",
        "summary_citation": "Reinsurer must compare expected vs actual settlement values.",
        "applies_to_transactions": "Reconciliation",
    },
    {
        "clause_id": "CLS-035",
        "category": "Reconciliation",
        "clause_title": "Auto-Accept Threshold",
        "summary_citation": "Variance <= 0.50% auto-accepted.",
        "applies_to_transactions": "Reconciliation",
    },
    {
        "clause_id": "CLS-036",
        "category": "Reconciliation",
        "clause_title": "Manual Review Threshold",
        "summary_citation": "Variance > 0.50% requires manual review.",
        "applies_to_transactions": "Reconciliation",
    },
    {
        "clause_id": "CLS-037",
        "category": "Reconciliation",
        "clause_title": "Compliance Escalation Threshold",
        "summary_citation": "Variance > 2.00% escalated to compliance review.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-038",
        "category": "Reconciliation",
        "clause_title": "Executive Review Threshold",
        "summary_citation": "Variance > CAD 2.5M requires executive review.",
        "applies_to_transactions": "Governance",
    },
    {
        "clause_id": "CLS-039",
        "category": "Reconciliation",
        "clause_title": "Reconciliation Triggers",
        "summary_citation": "Manual reconciliation triggered by late mortality reporting, assumption changes, duplicate records, benefit corrections.",
        "applies_to_transactions": "Reconciliation",
    },
    {
        "clause_id": "CLS-040",
        "category": "Reconciliation",
        "clause_title": "Historical Variance Review",
        "summary_citation": "Repeated variances over 3 consecutive periods trigger operational review.",
        "applies_to_transactions": "Governance",
    },
    {
        "clause_id": "CLS-041",
        "category": "Compliance",
        "clause_title": "Onboarding Screening Requirement",
        "summary_citation": "Cedants screened during onboarding.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-042",
        "category": "Compliance",
        "clause_title": "Periodic Screening Requirement",
        "summary_citation": "Active cedants screened monthly.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-043",
        "category": "Compliance",
        "clause_title": "Payment Screening Requirement",
        "summary_citation": "Screening required before settlement payment release.",
        "applies_to_transactions": "Payments, Compliance",
    },
    {
        "clause_id": "CLS-044",
        "category": "Compliance",
        "clause_title": "Screening Sources",
        "summary_citation": "Screening against OFAC, FinCEN, and FIS Prime.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-045",
        "category": "Compliance",
        "clause_title": "Compliance Hold Rule",
        "summary_citation": "Unresolved sanction match places settlement on Compliance Hold.",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-046",
        "category": "Collateral",
        "clause_title": "Collateral Threshold",
        "summary_citation": "Collateral required when exposure exceeds CAD 10M.",
        "applies_to_transactions": "Risk Management",
    },
    {
        "clause_id": "CLS-047",
        "category": "Collateral",
        "clause_title": "Eligible Collateral Types",
        "summary_citation": "Cash, government bonds, investment-grade securities permitted.",
        "applies_to_transactions": "Treasury",
    },
    {
        "clause_id": "CLS-048",
        "category": "Commutation",
        "clause_title": "Commutation Eligibility",
        "summary_citation": "Either party may request commutation after Year 10.",
        "applies_to_transactions": "Contract Termination",
    },
    {
        "clause_id": "CLS-049",
        "category": "Commutation",
        "clause_title": "Termination Valuation Basis",
        "summary_citation": "Termination value based on discount rates, projected liabilities, termination spread.",
        "applies_to_transactions": "Termination Calculation",
    },
    {
        "clause_id": "CLS-050",
        "category": "Audit",
        "clause_title": "Audit Retention Requirement",
        "summary_citation": "Operational records retained for 10 years after termination.",
        "applies_to_transactions": "Audit, Compliance",
    },
    {
        "clause_id": "CLS-051",
        "category": "Audit",
        "clause_title": "Audit Scope",
        "summary_citation": "Audit records maintained for file processing, calculations, reconciliations, approvals, overrides.",
        "applies_to_transactions": "Audit",
    },
    {
        "clause_id": "CLS-052",
        "category": "AI Governance",
        "clause_title": "AI-Assisted Processing Clause",
        "summary_citation": "IRiS AI may be used for file classification, anomaly detection, reconciliation support, sanction prioritization.",
        "applies_to_transactions": "AI Operations",
    },
    {
        "clause_id": "CLS-053",
        "category": "AI Governance",
        "clause_title": "Human Oversight Requirement",
        "summary_citation": "All material AI-assisted decisions require human oversight.",
        "applies_to_transactions": "Governance",
    },
    {
        "clause_id": "CLS-054",
        "category": "Default",
        "clause_title": "Failure to Pay Settlement",
        "summary_citation": "Failure to pay settlements constitutes event of default.",
        "applies_to_transactions": "Settlement",
    },
    {
        "clause_id": "CLS-055",
        "category": "Default",
        "clause_title": "Material Reporting Failure",
        "summary_citation": "Material reporting failures considered default event.",
        "applies_to_transactions": "Operations",
    },
    {
        "clause_id": "CLS-056",
        "category": "Default",
        "clause_title": "Repeated Screening Failure",
        "summary_citation": "Repeated sanction screening failures constitute default event.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-057",
        "category": "Default",
        "clause_title": "Regulatory Breach",
        "summary_citation": "Regulatory breaches constitute event of default.",
        "applies_to_transactions": "Compliance",
    },
    {
        "clause_id": "CLS-058",
        "category": "Legal",
        "clause_title": "Governing Law",
        "summary_citation": "Agreement governed under Ontario, Canada law.",
        "applies_to_transactions": "Legal",
    },
    {
        "clause_id": "CLS-059",
        "category": "Reporting",
        "clause_title": "Settlement Reconciliation SLA",
        "summary_citation": "Settlement reconciliation must complete within 2 business days.",
        "applies_to_transactions": "Operations",
    },
    {
        "clause_id": "CLS-060",
        "category": "Reporting",
        "clause_title": "Payment Release SLA",
        "summary_citation": "Payment release must complete within T+10 business days.",
        "applies_to_transactions": "Payments",
    },
]


def get_contract_clause_catalog() -> list[dict[str, str]]:
    return [dict(item) for item in CONTRACT_CLAUSE_CATALOG]


def get_contract_clauses_by_category(category: str) -> list[dict[str, str]]:
    return [dict(item) for item in CONTRACT_CLAUSE_CATALOG if item["category"].lower() == category.lower()]


def serialize_contract_clause_for_claims(item: dict[str, str]) -> dict[str, Any]:
    return {
        "clause_id": item["clause_id"],
        "clause_title": item["clause_title"],
        "category": item["category"],
        "status": "matched",
        "description": item["summary_citation"],
        "fields_affected": [],
        "active": True,
    }
